---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
  namespace: prod
spec:
  ports:
  - name: frontend
    port: 8000
    targetPort: 80
    protocol: TCP
  selector:
    run: frontend
  type: NodePort