---
apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: db
  labels:
    app: postgresql-db
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: postgresql-db
  type: ClusterIP