---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: backfront
  namespace: test
spec:
  ports:
  - name: frontend
    port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    run: backfront
  type: NodePort