apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "example-chart.fullname" . }}-db
  labels:
    {{- include "example-chart.labels" . | nindent 4 }}
    {{- toYaml .Values.labels.db | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount.db }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "example-chart.selectorLabels" . | nindent 6 }}
      {{- toYaml .Values.labels.db | nindent 6 }}
  serviceName: {{ include "example-chart.fullname" . }}-db
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "example-chart.selectorLabels" . | nindent 8 }}
        {{- toYaml .Values.labels.db | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Chart.Name }}-db
          image: "{{ .Values.image.db.repository }}:{{ .Values.image.db.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.db.pullPolicy }}
          ports:
            - containerPort: {{ .Values.endpoint.db }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env.db | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}