Vagrant.configure("2") do |config|
  config.disksize.size = '3GB'
  config.vm.define "master" do |master|
    master.vm.box = "bento/ubuntu-20.04"
    master.vm.network "private_network", ip: "192.168.10.21"
    master.vm.hostname = "master"
    master.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      end
    master.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/my_pc.pub"
    master.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/my_pc.pub >> /home/vagrant/.ssh/authorized_keys
      sudo echo "192.168.10.22 node1" | sudo tee -a /etc/hosts
      sudo echo "192.168.10.23 node2" | sudo tee -a /etc/hosts
      sudo echo "192.168.10.24 node3" | sudo tee -a /etc/hosts
      sudo echo "192.168.10.25 node4" | sudo tee -a /etc/hosts
      sudo timedatectl set-timezone Europe/Moscow
    SHELL
    end
  
    config.vm.define "node1" do |node1|
      node1.vm.box = "bento/ubuntu-20.04"
      node1.vm.network "private_network", ip: "192.168.10.22"
      node1.vm.hostname = "node1"
      node1.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
        end
      node1.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/my_pc.pub"
      node1.vm.provision "shell", inline: <<-SHELL
         cat /home/vagrant/.ssh/my_pc.pub >> /home/vagrant/.ssh/authorized_keys
         sudo echo "192.168.10.21 master" | sudo tee -a /etc/hosts
         sudo echo "192.168.10.23 node2" | sudo tee -a /etc/hosts
         sudo echo "192.168.10.24 node3" | sudo tee -a /etc/hosts
         sudo echo "192.168.10.25 node4" | sudo tee -a /etc/hosts
         sudo timedatectl set-timezone Europe/Moscow
      SHELL
      end
   
    config.vm.define "node2" do |node2|
      node2.vm.box = "bento/ubuntu-20.04"
      node2.vm.network "private_network", ip: "192.168.10.23"
      node2.vm.hostname = "node2"
      node2.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
        end
      node2.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/my_pc.pub"
      node2.vm.provision "shell", inline: <<-SHELL
         cat /home/vagrant/.ssh/my_pc.pub >> /home/vagrant/.ssh/authorized_keys
         sudo echo "192.168.10.21 master" | sudo tee -a /etc/hosts
         sudo echo "192.168.10.22 node1" | sudo tee -a /etc/hosts
         sudo echo "192.168.10.24 node3" | sudo tee -a /etc/hosts
         sudo echo "192.168.10.25 node4" | sudo tee -a /etc/hosts
         sudo timedatectl set-timezone Europe/Moscow
      SHELL
      end


    config.vm.define "node3" do |node3|
      node3.vm.box = "bento/ubuntu-20.04"
      node3.vm.network "private_network", ip: "192.168.10.24"
      node3.vm.hostname = "node3"
      node3.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
        end
      node3.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/my_pc.pub"
      node3.vm.provision "shell", inline: <<-SHELL
         cat /home/vagrant/.ssh/my_pc.pub >> /home/vagrant/.ssh/authorized_keys
         sudo echo "192.168.10.21 master" | sudo tee -a /etc/hosts
         sudo echo "192.168.10.22 node1" | sudo tee -a /etc/hosts
         sudo echo "192.168.10.23 node2" | sudo tee -a /etc/hosts
         sudo echo "192.168.10.25 node4" | sudo tee -a /etc/hosts
         sudo timedatectl set-timezone Europe/Moscow
      SHELL
      end

    config.vm.define "node4" do |node4|
      node4.vm.box = "bento/ubuntu-20.04"
      node4.vm.network "private_network", ip: "192.168.10.25"
      node4.vm.hostname = "node4"
      node4.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
        end
      node4.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/my_pc.pub"
      node4.vm.provision "shell", inline: <<-SHELL
          cat /home/vagrant/.ssh/my_pc.pub >> /home/vagrant/.ssh/authorized_keys
          sudo echo "192.168.10.21 master" | sudo tee -a /etc/hosts
          sudo echo "192.168.10.22 node1" | sudo tee -a /etc/hosts
          sudo echo "192.168.10.23 node2" | sudo tee -a /etc/hosts
          sudo echo "192.168.10.24 node3" | sudo tee -a /etc/hosts
          sudo timedatectl set-timezone Europe/Moscow
      SHELL
      end
  end
